name: Axolotl pipeline

on: [ push, pull_request ]

jobs:
  build-axolotl:
    name: Build axolotl
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -race ./...

      - name: Build
        run: go build -v

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: axolotl-${{ matrix.os }}-${{ github.run_number }}
          path: axolotl
          retention-days: 1

  build-axolotl-web:
    name: Build axolotl-web
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: npm --prefix ./axolotl-web ci

      - name: Run tests
        run: npm --prefix ./axolotl-web test

      - name: Lint application
        run: npm --prefix ./axolotl-web run lint

      - name: Build
        run: npm --prefix ./axolotl-web run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: axolotl-web-${{ github.run_number }}
          path: axolotl-web/dist/
          retention-days: 1

  package-appimage:
    name: Package as an AppImage
    needs: [build-axolotl, build-axolotl-web]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download axolotl and axolotl-web build artifacts
        uses: actions/download-artifact@v2
        with:
          path: bin

      - name: Setup appimagetool
        run: |
          curl -sLO https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Build the AppImage
        env:
          ARCH: x86_64
        run: |
          mkdir -p build/AppDir/usr/bin
          cp -f bin/axolotl-ubuntu-latest-${{ github.run_number }}/axolotl build/AppDir/usr/bin/axolotl
          chmod +x build/AppDir/usr/bin/axolotl

          mkdir -p build/AppDir/usr/bin/axolotl-web/dist
          cp -rf bin/axolotl-web-${{ github.run_number }}/* build/AppDir/usr/bin/axolotl-web/dist

          cp -f appimage/AppDir/AppRun build/AppDir/AppRun
          chmod +x build/AppDir/AppRun

          cp -f appimage/AppDir/axolotl.desktop build/AppDir/axolotl.desktop
          cp -f appimage/AppDir/axolotl.png build/AppDir/axolotl.png

          mkdir -p build/AppDir/usr/share/metainfo
          cp -f appimage/AppDir/axolotl.appdata.xml build/AppDir/usr/share/metainfo/axolotl.appdata.xml

          ./appimagetool-x86_64.AppImage build/AppDir

      - name: Upload the built AppImage artifact
        uses: actions/upload-artifact@v2
        with:
          name: Axolotl-x86_64-${{ github.run_number }}.AppImage
          path: Axolotl-x86_64.AppImage
          retention-days: 1

  package-flatpak:
    name: Package as a Flatpak
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Flatpak
        run: |
          sudo apt-get install flatpak flatpak-builder
          flatpak remote-add --user --verbose --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak-builder --version
          # flatpak install flathub org.flatpak.Builder

      - name: Build the Flatpak
        run: |
          flatpak-builder --user --install-deps-from=flathub --repo=repo build flatpak/org.nanuc.Axolotl.yml
          flatpak build-bundle repo axolotl.flatpak org.nanuc.Axolotl

      - name: Upload the built Flatpak artifact
        uses: actions/upload-artifact@v2
        with:
          retention-days: 1
